### NumPy Section:

 1. Install and import the NumPy library. Check its version

In [36]:
import numpy as np

In [39]:
print(np.__version__)

1.26.4


 2. Create a 1D NumPy array with elements from 0 to 9 using array()

In [41]:
arr =np.array([range(0,10)])

In [42]:
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

 3. Generate a 2D array with shape (3, 4) using arange().

In [48]:
arr1 = np.arange(10,22)
arr1.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

 4. Create an array of 5 equally spaced numbers between 0 and 1 using linspace()

In [50]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

5. Slice and extract a subarray from a 2D array of shape (4, 5).

In [60]:
a = np.arange(10,30).reshape(4,5)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [64]:
a[1:3,1:4]

array([[16, 17, 18],
       [21, 22, 23]])

 6. Reshape a 1D array of size 12 into a 3x4 matrix

In [74]:
arr = np.arange(1,13)
ar =arr.reshape(3,4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

 7. Print the shape, data type, and number of dimensions of an array

In [75]:
ar.shape

(3, 4)

In [76]:
ar.dtype

dtype('int32')

In [77]:
ar.ndim

2

 8. Perform element-wise addition and multiplication on two same-sized arrays

In [80]:
a1 = np.array([1,2,3,4])
a2 = np.array([10,20,30,40])
print("Addition:",a1+a2)
print("Multiplication:",a1*a2)

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]


 9. Demonstrate broadcasting with a 1D array and 2D array

In [86]:
d1 = np.array([10,20,30])
d2 = np.array([[1,2,3],
               [4,5,6]])
b = d1 + d2
print("Broadcasted array:\n",b)

Broadcasted array:
 [[11 22 33]
 [14 25 36]]


 10. Find the mean, standard deviation, and sum of a 2D array

In [87]:
b.mean()

23.5

In [88]:
b.std()


9.105858919765158

In [89]:
b.sum()

141

### Pandas section:

In [6]:
import pandas as pd
import numpy as np

 11. Create a Series of 5 numbers and assign custom labels

In [7]:
data = [10, 20, 30, 40, 50]
labels = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=labels)
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


12. Construct a DataFrame from a dictionary with student names, marks, and cities

In [8]:
stu_name = pd.Series(['shravani','payal','shreya','saee','apurva'])
marks = pd.Series([78,98,77,80,56])
cities = pd.Series(['pune','mumbai','satara','pune','nashik'])

In [9]:
df = pd.DataFrame({
    'stu_name':stu_name,
    'marks':marks,
    'cities':cities
})
df

stu_name  marks  cities
0  shravani     78    pune
1     payal     98  mumbai
2    shreya     77  satara
3      saee     80    pune
4    apurva     56  nashik

13. Create a DataFrame from a NumPy array and assign column names

In [10]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

columns = ['Col_A', 'Col_B', 'Col_C']
df1 = pd.DataFrame(array, columns=columns)
print(df1)


   Col_A  Col_B  Col_C
0      1      2      3
1      4      5      6
2      7      8      9


14. Use loc and iloc to select specific rows and columns from a DataFrame

In [11]:
df1.iloc[1:3,0:3]

Col_A  Col_B  Col_C
1      4      5      6
2      7      8      9

In [12]:
df.loc[:,['stu_name','marks']]

stu_name  marks
0  shravani     78
1     payal     98
2    shreya     77
3      saee     80
4    apurva     56

 15. Apply head(), tail(), shape, info(), and describe() to explore a DataFrame

In [13]:
df.head(3)

stu_name  marks  cities
0  shravani     78    pune
1     payal     98  mumbai
2    shreya     77  satara

In [14]:
df.tail(3)

stu_name  marks  cities
2   shreya     77  satara
3     saee     80    pune
4   apurva     56  nashik

In [15]:
df.shape

(5, 3)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   stu_name  5 non-null      object
 1   marks     5 non-null      int64 
 2   cities    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes


In [17]:
df.describe()

marks
count   5.000000
mean   77.800000
std    14.906374
min    56.000000
25%    77.000000
50%    78.000000
75%    80.000000
max    98.000000

 16. Sort a DataFrame by values in a column using sort_values()

In [18]:
df.sort_values(by = 'marks')

stu_name  marks  cities
4    apurva     56  nashik
2    shreya     77  satara
0  shravani     78    pune
3      saee     80    pune
1     payal     98  mumbai

17. Sort a DataFrame based on the index using sort_index()

In [19]:
df.sort_index()

stu_name  marks  cities
0  shravani     78    pune
1     payal     98  mumbai
2    shreya     77  satara
3      saee     80    pune
4    apurva     56  nashik

18. Filter rows in a DataFrame where a column (e.g., marks) is greater than a threshold

In [20]:
df[df['marks']>80]

stu_name  marks  cities
1    payal     98  mumbai

19. Group a DataFrame by a column (e.g., city) and calculate the average marks

In [21]:
gr = df.groupby('cities')

In [22]:
gr['marks'].mean()

cities
mumbai    98.0
nashik    56.0
pune      79.0
satara    77.0
Name: marks, dtype: float64

 20. Use agg() to apply multiple aggregation functions (mean, min, max) on a grouped DataFrame.

In [23]:
res = df.groupby('cities').agg({
    'marks':['mean','min','max']
    })
print(res)

       marks        
        mean min max
cities              
mumbai  98.0  98  98
nashik  56.0  56  56
pune    79.0  78  80
satara  77.0  77  77


 21. Merge two DataFrames on a common column (e.g., student ID)

In [29]:
df1 = pd.DataFrame({
    'stu_id':pd.Series([101,102,103,104,105]),
    'stu_name':pd.Series(['shravani','payal','shreya','saee','apurva']),
    'age':pd.Series([18,16,12,17,15])
})
df1

stu_id  stu_name  age
0     101  shravani   18
1     102     payal   16
2     103    shreya   12
3     104      saee   17
4     105    apurva   15

In [30]:
df2 = pd.DataFrame({
    'stu_id':pd.Series([101,102,103,104,105]),
    'marks':pd.Series([68,90,88,76,56]),
     
})
df2

stu_id  marks
0     101     68
1     102     90
2     103     88
3     104     76
4     105     56

In [31]:
df1.merge(df2)

stu_id  stu_name  age  marks
0     101  shravani   18     68
1     102     payal   16     90
2     103    shreya   12     88
3     104      saee   17     76
4     105    apurva   15     56

 22. Concatenate two DataFrames vertically and reset the index

In [35]:
pd.concat([df1,df2],axis = 0).reset_index(drop = True)

stu_id  stu_name   age  marks
0     101  shravani  18.0    NaN
1     102     payal  16.0    NaN
2     103    shreya  12.0    NaN
3     104      saee  17.0    NaN
4     105    apurva  15.0    NaN
5     101       NaN   NaN   68.0
6     102       NaN   NaN   90.0
7     103       NaN   NaN   88.0
8     104       NaN   NaN   76.0
9     105       NaN   NaN   56.0