##### 1.Crreate a numPy array of shape(3,3) with values ranging from 1 to 9

In [4]:
import numpy as np
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 2. Given a 1D NumPy array [10,20,30,40,50],write code to reverse the array

In [6]:
a =np.array([10,20,30,40,50])
print("Reversed array:",a[: :-1])

Reversed array: [50 40 30 20 10]


##### 3. Create a 5x5 NumPy array filled with zeros and set the value of the middle element to 1

In [9]:
arr = np.zeros((5, 5))
arr[2, 2] = 1
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##### 4.generate a numpy array with 20 random integers between 1 to 100(replace all even number with -1)

In [10]:
arr = np.random.randint(1, 101, size=20)  
for i in range(len(arr)):
    if arr[i] % 2 == 0:
        arr[i] = -1

print(arr)


[-1 27 49 -1 -1 29 -1 -1 -1  1 95 53  9 -1 43 83 -1 89 25 95]


##### 5.Given a NumPy array a = np.array([[1, 2], [3, 4], [5, 6]]) , extract the second column.



In [11]:
a = np.array([[1,2],[3,4],[5,6]])
a[0:3,[1]]

array([[2],
       [4],
       [6]])

##### 6.Create a NumPy array with values [1, 2, 3, 4] and convert it into a 2x2 matrix.

In [14]:
a =np.array([1,2,3,4])
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

##### 7.Create two NumPy arrays of shape (2, 2) and perform element-wise addition, subtraction, multiplication, and division

In [20]:
a = np.array([[10,20],[30,40]])
b = np.array([[11,22],[33,44]])
res = np.empty((2, 2), dtype=float)
res[0, 0] = a[0, 0] + b[0, 0]        
res[0, 1] = a[0, 1] / b[0, 1]        
res[1, 0] = a[1, 0] - b[1, 0]        
res[1, 1] = a[1, 1] * b[1, 1]  
print("Array A:\n", a)
print("Array B:\n", b)
print("\nCustom Operation Result:\n", res)


Array A:
 [[10 20]
 [30 40]]
Array B:
 [[11 22]
 [33 44]]

Custom Operation Result:
 [[ 2.10000000e+01  9.09090909e-01]
 [-3.00000000e+00  1.76000000e+03]]


##### 8.Use NumPy to create an array of 10 linearly spaced values between 0 and 1.

In [21]:
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


##### 9.Create a NumPy array and demonstrate how to compute its mean, median, and standard deviation.

In [26]:
arr = np.array([23,45,67,55,34])
print("Array :",arr)
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("standard:",np.std(arr))

Array : [23 45 67 55 34]
mean: 44.8
median: 45.0
standard: 15.419468213917106


##### 10.Given a 2D NumPy array, write a function to normalize each column (subtract mean and divide by std deviation)

In [27]:
def normalize_cols(arr):
    mean = np.mean(arr, axis=0)      
    std = np.std(arr, axis=0)   
    std[std == 0] = 1
    normalize = (arr - mean) / std
    return normalize
a = np.array([[12,13],[34,56]])
res = normalize_cols(a)
print(res)
    

[[-1. -1.]
 [ 1.  1.]]
