In [3]:
import numpy as np

In [4]:
arr = np.array([23,45,67,89,10])

In [5]:
print(arr)

[23 45 67 89 10]


In [6]:
arr

array([23, 45, 67, 89, 10])

In [7]:
 type(arr)

numpy.ndarray

In [8]:
arr[2]

67

In [9]:
arr[2]= 30 # mutablea

In [10]:
arr

array([23, 45, 30, 89, 10])

In [11]:
arr[2]=10

In [12]:
arr


array([23, 45, 10, 89, 10])

In [13]:
arr1 = np.array([12,34,98,55,True,"pune"]) ## homogeneous

In [14]:
arr1

array(['12', '34', '98', '55', 'True', 'pune'], dtype='<U11')

In [15]:
arr1[5]

'pune'

In [16]:
arr1.dtype

dtype('<U11')

In [17]:
arr

array([23, 45, 10, 89, 10])

In [18]:
arr * 2

array([ 46,  90,  20, 178,  20])

### check which one is faster .... list or array

In [26]:
import time

In [27]:
time.time()

1750658300.1846833

In [28]:
s = 100000
list1 = list(range(s))
arr1 = np.array(list1)

In [29]:
# for list
start_time = time.time()
x =[i*2 for i in list1]
time_list = time.time() - start_time
print("time taken by list:",time_list)

time taken by list: 0.016424179077148438


In [30]:
# for array
start_time = time.time()
y = arr1*2
time_arr = time.time() - start_time
print("time taken by arr:",time_arr)

time taken by arr: 0.0018792152404785156


In [31]:
# arangne

In [32]:
a =  np.arange(10)

In [33]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [41]:
arr.ndim

1

In [42]:
## 2-d array

In [48]:
arr = np. array([[1,2,3],[4,5,6],[8,5,3],[6,4,1]])

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 5, 3],
       [6, 4, 1]])

In [50]:
arr.size

12

In [51]:
arr.shape

(4, 3)

In [52]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 8, 5, 3, 6, 4, 1])

In [53]:
arr.flatten().ndim

1

In [54]:
arr.reshape(6,2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 5],
       [3, 6],
       [4, 1]])

In [57]:
arr.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [8, 5, 3, 6, 4, 1]])

In [58]:
arr.reshape(2,-1)

array([[1, 2, 3, 4, 5, 6],
       [8, 5, 3, 6, 4, 1]])

In [60]:
arr.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 5],
       [3, 6],
       [4, 1]])

In [61]:
arr.reshape(2,6,1)

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[8],
        [5],
        [3],
        [6],
        [4],
        [1]]])

In [62]:
arr.reshape(3,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [8, 5]],

       [[3, 6],
        [4, 1]]])

In [63]:
# slicing

In [64]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 5, 3],
       [6, 4, 1]])

In [65]:
arr1 = np.arange(3,13)
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
arr1[3:7]

array([6, 7, 8, 9])

In [67]:
arr[1:3,0:2]

array([[4, 5],
       [8, 5]])

In [68]:
arr[1:3,0:3]

array([[4, 5, 6],
       [8, 5, 3]])

In [69]:
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
np.mean(arr1)

7.5

In [71]:
np.std(arr1)

2.8722813232690143

#### linear alg

In [72]:
a = np.array([[1,4],[4,9]])
b = np.array([[3,3],[10,1]])


In [73]:
a

array([[1, 4],
       [4, 9]])

In [74]:
b

array([[ 3,  3],
       [10,  1]])

In [79]:
a @ b

array([[ 43,   7],
       [102,  21]])

In [80]:
np.dot(a,b)

array([[ 43,   7],
       [102,  21]])

In [81]:
a

array([[1, 4],
       [4, 9]])

In [82]:
np.linalg.det(a)

-6.999999999999999

In [83]:
np.linalg.inv(a)

array([[-1.28571429,  0.57142857],
       [ 0.57142857, -0.14285714]])

In [84]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.65685425, 10.65685425]), eigenvectors=array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]]))

In [85]:
# vector

vec = np.array([3,6])

In [86]:
np.linalg.norm(vec)

6.708203932499369

In [1]:
help(np.linalg.norm(vec))

NameError: name 'np' is not defined

## problems

1.Crreate a numPy array of shape(3,3) with values ranging from 1 to 9

In [93]:
arr = np.arange(0,9)

In [94]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2. Given a 1D NumPy array [10,20,30,40,50],write code to reverse the array

In [98]:
a =np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [104]:
a[: :-1]

array([50, 40, 30, 20, 10])

3. Create a 5x5 NumPy array filled with zeros and set the value of the middle element to 1

In [106]:
arr = np.zeros((5, 5))
arr[2, 2] = 1
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4.generate a numpy array with 20 random integers between 1 to 100(replace all even number with -1)

4.generate a numpy array with 20 random integers between 1 to 100(replace all even number with -1)

In [4]:
arr = np.arange(1,101,dtype = int)
for i in range(len(arr)):
    if arr[i] % 2 == 0:
        arr[i] = -1
print(arr)


NameError: name 'np' is not defined